const BREED_NAMES = [
  "Affenpinscher",
  "Airedale terrier",
  "Akita",
  "Akita amerykańska",
  "Alaskan malamute",
  "Amerykański cocker spaniel",
  "Amerykański staffordshire terrier",
  "Appenzeller",
  "Australijski pies pasterski",
  "Australian silky terrier",
  "Azawakh",
  "Basenji",
  "Basset artezyjsko-normandzki",
  "Basset hound",
  "Beagle",
  "Bearded collie",
  "Beauceron",
  "Bedlington terrier",
  "Bernardyn",
  "Berneński pies pasterski",
  "Bichon frise",
  "Bichon hawański",
  "Bloodhound",
  "Bokser",
  "Bolończyk",
  "Border collie",
  "Border terrier",
  "Boston terrier",
  "Bouvier des Flandres",
  "Brabantczyk",
  "Briard",
  "Buldog angielski",
  "Buldog francuski",
  "Bulmastif",
  "Bulterier",
  "Bulterier miniaturowy",
  "Cairn terrier",
  "Cane corso",
  "Cavalier king charles spaniel",
  "Charcik włoski",
  "Chart afgański",
  "Chart polski",
  "Chart rosyjski borzoj",
  "Chesapeake bay retriever",
  "Chihuahua",
  "Chin japoński",
  "Chiński grzywacz",
  "Chow chow",
  "Clumber spaniel",
  "Cocker spaniel angielski",
  "Collie długowłosy",
  "Collie krótkowłosy",
  "Coton de tulear",
  "Curly coated retriever",
  "Czarny terier rosyjski",
  "Dalmatyńczyk",
  "Dandie dinmont terrier",
  "Deerhound",
  "Doberman",
  "Dog argentyński",
  "Dog bordoski",
  "Dog kanaryjski",
  "Dog niemiecki",
  "Duży szwajcarski pies pasterski",
  "Entlebucher",
  "Eurasier",
  "Fila brasileiro",
  "Flat coated retriever",
  "Foksterier krótkowłosy",
  "Foksterier szorstkowłosy",
  "Golden retriever",
  "Gończy polski",
  "Gończy słowacki",
  "Greyhound",
  "Gryfonik belgijski",
  "Gryfonik brukselski",
  "Hiszpański pies dowodny",
  "Hovawart",
  "Irish soft coated wheaten terrier",
  "Jack russell terrier",
  "Jamnik",
  "Jamnik długowłosy",
  "Jamnik krótkowłosy",
  "Jamnik króliczy",
  "Jamnik miniaturowy",
  "Jamnik szorstkowłosy",
  "Kelpie australijski",
  "Kerry blue terrier",
  "Komondor",
  "Kooikerhondje",
  "Kuvasz",
  "Labrador retriever",
  "Lagotto romagnolo",
  "Lakeland terrier",
  "Landseer",
  "Leonberger",
  "Lhasa apso",
  "Maltańczyk",
  "Manchester terrier",
  "Mastif",
  "Mastif hiszpański",
  "Mastif neapolitański",
  "Mastif tybetański",
  "Mieszaniec",
  "Mops",
  "Niemiecki terier myśliwski",
  "Norfolk terrier",
  "Norwich terrier",
  "Nova scotia duck tolling retriever",
  "Nowofundland",
  "Ogar polski",
  "Owczarek anatolijski",
  "Owczarek australijski",
  "Owczarek belgijski groenendael",
  "Owczarek belgijski laekenois",
  "Owczarek belgijski malinois",
  "Owczarek belgijski tervueren",
  "Owczarek bergamaski",
  "Owczarek chorwacki",
  "Owczarek holenderski",
  "Owczarek kataloński",
  "Owczarek kaukaski",
  "Owczarek maremmano-abruzzese",
  "Owczarek niemiecki",
  "Owczarek niemiecki długowłosy",
  "Owczarek pirenejski",
  "Owczarek podhalański",
  "Owczarek staroangielski",
  "Owczarek szetlandzki",
  "Owczarek szwajcarski biały",
  "Owczarek środkowoazjatycki",
  "Papillon",
  "Parson russell terrier",
  "Pekińczyk",
  "Pies faraona",
  "Pinczer miniaturowy",
  "Pinczer niemiecki",
  "Pirenejski pies górski",
  "Podenco ibicenco",
  "Pointer",
  "Polski owczarek nizinny",
  "Portugalski pies dowodny",
  "Posokowiec bawarski",
  "Posokowiec hanowerski",
  "Pudel duży",
  "Pudel miniaturowy",
  "Pudel średni",
  "Pudel toy",
  "Puli",
  "Pumi",
  "Rhodesian ridgeback",
  "Rosyjski toy",
  "Rottweiler",
  "Saluki",
  "Samojed",
  "Scottish terrier",
  "Sealyham terrier",
  "Seter angielski",
  "Seter irlandzki czerwono-biały",
  "Seter irlandzki czerwony",
  "Seter szkocki gordon",
  "Shar pei",
  "Shiba",
  "Shih tzu",
  "Siberian husky",
  "Skye terrier",
  "Spaniel bretoński",
  "Spaniel tybetański",
  "Spinone italiano",
  "Springer spaniel angielski",
  "Springer spaniel walijski",
  "Staffordshire bull terrier",
  "Szpic fiński",
  "Szpic japoński",
  "Szpic miniaturowy",
  "Szpic niemiecki",
  "Szpic wilczy",
  "Sznaucer miniaturowy",
  "Sznaucer olbrzym",
  "Sznaucer średni",
  "Terier irlandzki",
  "Terier tybetański",
  "Tosa",
  "Welsh corgi cardigan",
  "Welsh corgi pembroke",
  "Welsh terrier",
  "West highland white terrier",
  "Whippet",
  "Wilczak czechosłowacki",
  "Wilczak saarlooski",
  "Wilczarz irlandzki",
  "Wyżeł niemiecki krótkowłosy",
  "Wyżeł niemiecki szorstkowłosy",
  "Wyżeł polski",
  "Wyżeł weimarski",
  "Wyżeł węgierski krótkowłosy",
  "Wyżeł węgierski szorstkowłosy",
  "Wyżeł włoski",
  "Yorkshire terrier",
];

export const BREEDS: readonly string[] = [...BREED_NAMES].sort((a, b) => a.localeCompare(b, "pl"));
